apiVersion: v1
kind: Service
metadata:
  name: web-app-atc-service
spec:
  selector:
    app: web-app-atc-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
